### ISSUE TITLE
add missing applications

### ISSUE THREAD

**Issue by Bactobene** [BirdMakingStuff/rbx-scraper#1]
https://clientsettingscdn.roblox.com/v2/settings/application/GoogleAndroidApp
https://clientsettingscdn.roblox.com/v2/settings/application/RCCBootstrapper
https://clientsettingscdn.roblox.com/v2/settings/application/PCClientBootstrapperCJV
https://clientsettingscdn.roblox.com/v2/settings/application/PCStudioBootstrapperCJV
https://clientsettingscdn.roblox.com/v2/settings/application/MacClientBootstrapperCJV
https://clientsettingscdn.roblox.com/v2/settings/application/MacStudioBootstrapperCJV
https://clientsettingscdn.roblox.com/v2/settings/application/MacStudioAppCJV
https://clientsettingscdn.roblox.com/v2/settings/application/MacDesktopClientCJV

**Comment by BirdMakingStuff** [comment]
welcome to my side of the world!
I might add `GoogleAndroidApp` and `RCCBootstrapper`, but not the CJVs as they end up making the repo too cluttered (and there is low demand for them)
