### ISSUE TITLE
Add missing namespaces

### ISSUE THREAD

**Issue by Bactobene** [BirdMakingStuff/rbx-scraper#4]
CreatorDashboard.PriceOptimization.json
CreatorDashboard.StoreAnalytics.json
CreatorDashboard.MarketplaceOnboarding.json
CreatorDashboard.DataCollection.json
CreatorDashboard.Settings.json
CreatorDashboard.DataSharingSettingsV2.json
CreatorDashboard.AssetUpload.json
CreatorDashboard.Payouts.json
CreatorDashboard.Badges.json
CreatorDashboard.DevStatsExport.json
CreatorDashboard.SafetyControls.json
CreatorDashboard.ShareLinksManagament.json
CreatorDashboard.ComputeTelemetry.json
CreatorDashboard.LogIn.json
CreatorDashboard.HomepageTour.json
CreatorDashboard.ShareLinkAnalytics.json
CreatorDashboard.ShareLinkPromo.json
CreatorDashboard.AssetAnalytics.json
CreatorDashboard.Preferences.json
CreatorDashboard.Metadata.json
CreatorDashboard.DevStatsGame.json
CreatorDashboard.SignUp.json
CreatorDashboard.DataCollectionTerms.json
CreatorDashboard.Secrets.json
CreatorDashboard.DeveloperLanding.json

CreatorDocumentation.Navigation.json

**Comment by BirdMakingStuff** [comment]
welp

**Comment by BirdMakingStuff** [comment]
unlikely we'll do Creator Docs but all the rest have been added
