### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by idontyboi** [BirdMakingStuff/rbx-scraper#5]
Feature.QNAB.json (AI Assistant): https://create.roblox.com/c1851432215fef8a66ad0eebd4f62202d618b253/locales/en-US/Feature.QNAB.json
CreatorDashboard.OwnershipTransfer.json (Game ownership transfers) https://create.roblox.com/c1851432215fef8a66ad0eebd4f62202d618b253/locales/en-US/CreatorDashboard.OwnershipTransfer.json
Experience.Genre.json (All possible genres): https://create.roblox.com/c1851432215fef8a66ad0eebd4f62202d618b253/locales/en-US/Experience.Genre.json
CreatorDashboard.FiatPaidAccess.json (Self explanatory): https://create.roblox.com/c1851432215fef8a66ad0eebd4f62202d618b253/locales/en-US/CreatorDashboard.FiatPaidAccess.json
CreatorDashboard.AssetPrivacy.json (Self explanatory): https://create.roblox.com/c1851432215fef8a66ad0eebd4f62202d618b253/locales/en-US/CreatorDashboard.AssetPrivacy.json

**Comment by BirdMakingStuff** [comment]
I probably should fix it up properly one day to automatically scrape these.

Anyways, implemented in the latest commit.
